default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 5

development:
  <<: *default
  database: logistique_development

test:
  <<: *default
  database: logistique_test

production:
  <<: *default
  database: logistique_production
  username: logistique
  password: <%= ENV['LOGISTIQUE_DATABASE_PASSWORD'] %>
